# ==============================================================================
# Use Case: Kubernetes Service - Cassandra
# Description: Exposes the cassandra deployment internally.
# 
# Explanation: This file is part of the k8s suite. It provides a standardized template for cassandra-service.yaml to maintain infrastructure and application reliability.
# 
# How to Use:
# Run 'kubectl apply -f cassandra-service.yaml' to deploy this resource to your Kubernetes cluster.
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
