# ==============================================================================
# Use Case: Kubernetes Deployment - Mongodb
# Description: Deploys mongodb as a scalable pod in Kubernetes.
# 
# Explanation: This file is part of the k8s suite. It provides a standardized template for mongodb-deployment.yaml to maintain infrastructure and application reliability.
# 
# How to Use:
# Run 'kubectl apply -f mongodb-deployment.yaml' to deploy this resource to your Kubernetes cluster.
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb:latest
        ports:
        - containerPort: 8080
