# ==============================================================================
# Use Case: Kubernetes Service - Rabbitmq
# Description: Exposes the rabbitmq deployment internally.
# 
# Explanation: This file is part of the k8s suite. It provides a standardized template for rabbitmq-service.yaml to maintain infrastructure and application reliability.
# 
# How to Use:
# Run 'kubectl apply -f rabbitmq-service.yaml' to deploy this resource to your Kubernetes cluster.
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
