# ==============================================================================
# Use Case: Kubernetes Deployment - Rabbitmq
# Description: Deploys rabbitmq as a scalable pod in Kubernetes.
# 
# Explanation: This file is part of the k8s suite. It provides a standardized template for rabbitmq-deployment.yaml to maintain infrastructure and application reliability.
# 
# How to Use:
# Run 'kubectl apply -f rabbitmq-deployment.yaml' to deploy this resource to your Kubernetes cluster.
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 8080
