# ==============================================================================
# Use Case: Containerize Apache
# Description: Custom Docker image for apache with security hardening.
# 
# Explanation: This file is part of the Docker suite. It provides a standardized template for Dockerfile.apache to maintain infrastructure and application reliability.
# 
# How to Use:
# Run 'docker build -t apache-app -f Dockerfile.apache .' to build the image locally.
# ==============================================================================
FROM apache:latest
RUN apt-get update && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*
COPY ./custom-apache.conf /etc/apache/apache.conf
EXPOSE 8080
CMD ["apache"]
